Using Onvif events in a node app leads to infrequent unhandled exeptions as follows:
```
Error: You should create pull-point subscription first!
    at Cam.pullMessages (/home/pi/backend/node_modules/onvif/lib/events.js:188:10)
    at Cam._eventPull (/home/pi/backend/node_modules/onvif/lib/events.js:308:9)
    at Cam.<anonymous> (/home/pi/backend/node_modules/onvif/lib/events.js:100:13)
    at parseSOAPString (/home/pi/backend/node_modules/onvif/lib/utils.js:108:3)
    at IncomingMessage.<anonymous> (/home/pi/backend/node_modules/onvif/lib/cam.js:270:4)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Changes:
- In line 289 an additinal check regarding events.subscription is introduced, since `pullMessages` will throw otherwise.
- Added several missing semicolons.